// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3bhxtefDzUY3qjWNzledTih4HFN-fPsI',
    appId: '1:105587215891:web:c6610789878d937ad639e6',
    messagingSenderId: '105587215891',
    projectId: 'chat-char',
    authDomain: 'chat-char.firebaseapp.com',
    storageBucket: 'chat-char.appspot.com',
    measurementId: 'G-E5CE6NVM5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjE6t596r14i28xLinwcaha0ulchOc0DA',
    appId: '1:105587215891:android:1b025d36b8b6749ad639e6',
    messagingSenderId: '105587215891',
    projectId: 'chat-char',
    storageBucket: 'chat-char.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfIf2WETYLJa-rPwtl4TIpXzOwoUfOzWs',
    appId: '1:105587215891:ios:5db2ed1aeef84de4d639e6',
    messagingSenderId: '105587215891',
    projectId: 'chat-char',
    storageBucket: 'chat-char.appspot.com',
    iosClientId: '105587215891-8h5pho1mq0ni2dp6pkuarsqurtubjhpp.apps.googleusercontent.com',
    iosBundleId: 'com.willhuffman.char',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfIf2WETYLJa-rPwtl4TIpXzOwoUfOzWs',
    appId: '1:105587215891:ios:5db2ed1aeef84de4d639e6',
    messagingSenderId: '105587215891',
    projectId: 'chat-char',
    storageBucket: 'chat-char.appspot.com',
    iosClientId: '105587215891-8h5pho1mq0ni2dp6pkuarsqurtubjhpp.apps.googleusercontent.com',
    iosBundleId: 'com.willhuffman.char',
  );
}
